### ISSUE TITLE
Change AudioItem's url value

### ISSUE THREAD

**Issue by ghost** [delannoyk/AudioPlayer#100]
Is there a way to change AudioItem's url value? 
I have this:
AudioItemURL(quality: KDEAudioPlayer.AudioQuality.medium, url: http://xxxxxxx.com.br/static/media/musics/XXXXXXX.mp3)

**Comment by delannoyk** [comment]
Hey @ghost
What are you exactly trying to achieve? You can change the url by creating a new item but the url cannot change overtime.
