### ISSUE TITLE
How to use...

### ISSUE THREAD

**Issue by sirvon** [delannoyk/AudioPlayer#106]
let delegate: AudioPlayerDelegate = ...

What's supposed to go in replace of the ...?

thanks!

**Comment by delannoyk** [comment]
An instance of AudioPlayerDelegate that you have created.
https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/Protocols.html

**Comment by sirvon** [comment]
I acutally spent the whole last week wrapping my head around protocols, not from a copy and paste standpoint but from actually knowing what and how to...I'm still not there...

Can you give an example to increase my understanding.

thank you!

**Comment by sirvon** [comment]
can it be..... ```delegate: AudioPlayerDelegate = self ``` ?
If I conform a ViewController to AudioPlayerDelegate

```
class MyViewController: AudioPlayerDelegate {

       let delegate: AudioPlayerDelegate = self
}
```

**Comment by delannoyk** [comment]
@sirvon yes for sure it can.
