### ISSUE TITLE
what settings should I set to play song from URl as fast as possible?

### ISSUE THREAD

**Issue by bizibizi** [delannoyk/AudioPlayer#117]

**Comment by jadsonlourenco** [comment]
Using a stream(VOD) source?

**Comment by bizibizi** [comment]
do not sure what's that. 

I want to play mp3 from url without buffering(without waiting for it!)

**Comment by jadsonlourenco** [comment]
If you set the url to a mp3 file directly it will download the file to begin play it, so, to start the playback instantly you need a "stream" url, in this case I recommend HLS (search on google).

If you need a stream server: https://github.com/kaltura/nginx-vod-module

**Comment by bizibizi** [comment]
@jadsonlourenco ok, I see. So, I am able to save that .mp3 then?

**Comment by jadsonlourenco** [comment]
Yes, if you are using iOS 10+: https://github.com/r-plus/HLSion

**Comment by bizibizi** [comment]
@jadsonlourenco 9.0 :( 
well, maybe you can recommend me some library which does: 

- start playing .mp3 from url immediately (like streaming or streaming)
- cache it and track caching progress during it's playback
- save cached file to local storage

**Comment by jadsonlourenco** [comment]
Well:
* AVPlayer
* iOS 10+ has this feature by default (https://developer.apple.com/library/content/documentation/AudioVideo/Conceptual/MediaPlaybackGuide/Contents/Resources/en.lproj/HTTPLiveStreaming/HTTPLiveStreaming.html) but I think this lib more convenient: https://github.com/r-plus/HLSion
* The same lib as before
