### ISSUE TITLE
Offline playback of ipod-library:// items fails when it doesn't need to

### ISSUE THREAD

**Issue by dslysenko** [delannoyk/AudioPlayer#12]
Offline playback of an item from the device's media library is very much possible using KDEAudioPlayer without further modifications, but is unfortunately blocked because of slightly overzealous logic for rejecting offline playback. Just like file URLs, ipod-library URLs can be played back offline.

See https://gitlab.com/riff/AudioPlayer/commit/2213d7801b66d6d001e776ba3a3eb040a65eace3 for a fix that worked for me.

**Comment by delannoyk** [comment]
You're right, I didn't think about that case.

Thanks, I'll look into it ASAP.

**Comment by delannoyk** [comment]
Let me know if that works out for you :)
