### ISSUE TITLE
Swift 4 support

### ISSUE THREAD

**Issue by kidcosmic** [delannoyk/AudioPlayer#121]
AudioPlayer doesnt build with Swift 4

**Comment by jadsonlourenco** [comment]
Well, IOS 11 was released few days ago and I think is time to @delannoyk release a new version with Swift 4 support. I've cloned this repo and using XCode 9 to convert automatically to Swift 4 worked, but still need fix manually this file `AudioItem.swift` and replace the last function with this:
```
open func parseMetadata(_ items: [AVMetadataItem]) {
        items.forEach {
            if let commonKey = $0.commonKey {
                switch commonKey {
                case AVMetadataCommonKeyTitle where title == nil:
                    title = $0.value as? String
                case AVMetadataCommonKeyArtist where artist == nil:
                    artist = $0.value as? String
                case AVMetadataCommonKeyAlbumName where album == nil:
                    album = $0.value as? String
                case AVMetadataID3MetadataKeyTrackNumber where trackNumber == nil:
                    trackNumber = $0.value as? NSNumber
                case AVMetadataCommonKeyArtwork where artwork == nil:
                    artworkImage = ($0.value as? Data).flatMap { Image(data: $0) }
                default:
                    break
                }
            }
        }
    }
```

I don't know how to push and I think need more than this, like run and pass the "tests" of the code, before send a PR. But I think is not much hard fix this package to work with Swift 4, I hope to see it soon. 

Thank you @delannoyk for this project.

**Comment by delannoyk** [comment]
I know this is long due but I just updated the project to Xcode 9.3 (swift 4.1). It's available on master, will likely create a new release soon.

**Comment by 7yon** [comment]
@delannoyk When will the support for swift 4?
