### ISSUE TITLE
Strange memory leak 

### ISSUE THREAD

**Issue by SerhiiMatvieiev** [delannoyk/AudioPlayer#126]
When I start playing audio items I have this memory leak, look at screen below:
<img width="1440" alt="screen shot 2017-11-16 at 10 42 54 am" src="https://user-images.githubusercontent.com/14834451/32881876-44a05ec0-cabb-11e7-8565-dec60e5a49c5.png">

Anybody now how to fix it? Or where I can find this leak in code?

**Comment by delannoyk** [comment]
The responsible framework is AudioToolbox so as far as I know there's not much that we can do.
