### ISSUE TITLE
Suggestion: queue items should be public read

### ISSUE THREAD

**Issue by frogcjn** [delannoyk/AudioPlayer#13]
I think it is not easy to track audioItem index outside of the AudioPlayer

because you have public function to use the index for removing audioItem, so it is necessary to know the index of the audioItem.

        removeItemAtIndex(index: Int)

so I think the queuedItems should be at least public read from outside.
And it is good for developer to show users what items are in the queue.

Thanks!

**Comment by frogcjn** [comment]
And after test, I think there is an issue with background session that it is cannot control music over music control panel, and cannot play next though the system control. Is it better to use AVQueuePlayer?

**Comment by delannoyk** [comment]
Hi,
We're talking about 2 different issues here.

So 
1/ I agree, I'll expose this later today.
2/ I'm not able to reproduce this. Could you explain a bit more? Anyway, I didn't use AVQueuePlayer to have more control on the queue and on items (such as auto quality adjustment, shuffle/repeat mode, ...).

**Comment by frogcjn** [comment]
audioPlayer.addItemToQueue(audioItem)

I just use this API, and after that, I cannot control music through the music center system control, and it is not entering background mode. (I have played music in iTunes before, so the music center showed the item queue of Apple's Music app)

the background mode begins after I call this method:

    audioPlayer.next()

though I called this API, the background mode is still working well.

**Comment by delannoyk** [comment]
I'll check it out later today and I'll let you know :)

**Comment by delannoyk** [comment]
There's now a public property to get the current queue.

Looking into your issue right now.

**Comment by frogcjn** [comment]
Thanks!

**Comment by delannoyk** [comment]
I still cannot reproduce.

Anyway, let's check a basic requirement. Did you add
```
	<key>UIBackgroundModes</key>
	<array>
		<string>audio</string>
	</array>
```
in your app's Info.plist?

**Comment by frogcjn** [comment]
I think I just need MPNowPlayingInfoCenter

**Comment by delannoyk** [comment]
Nah!

Did you do this: https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIApplication_Class/#//apple_ref/occ/instm/UIApplication/beginReceivingRemoteControlEvents
?

**Comment by delannoyk** [comment]
@frogcjn did it help? Are you still stuck with this issue?

**Comment by frogcjn** [comment]
Thanks! I solved the problem.
