### ISSUE TITLE
Audio state not updating on longer songs

### ISSUE THREAD

**Issue by adelburekovic** [delannoyk/AudioPlayer#131]
```func audioPlayer(_ audioPlayer: AudioPlayer, didChangeStateFrom from: AudioPlayerState, to state: AudioPlayerState)``` method works without issues on songs of smaller length. 

For songs of the length of 15min, for instance, I don't get audio player state update after the song finishes.

Did anyone notice a similar problem?

**Comment by delannoyk** [comment]
Hi @adelburekovic 

I'm using this project for mixtapes that are over 60minutes long and I don't have this issue. Would you have more context for me to reproduce/track this issue?

Cheers.
