### ISSUE TITLE
It show some waring in Xcode9.3 and swift4.1

### ISSUE THREAD

**Issue by a1259667899** [delannoyk/AudioPlayer#132]
like this
`'dynamic' var 'trackNumber' must also be '@objc'`

**Comment by delannoyk** [comment]
@a1259667899 Just updated it on master. Please reopen the issue if it doesn't fix your problems.

**Comment by havocked** [comment]
There is still a problem, it seems that I cannot get the version 1.2 of the pod. I only fetch the 1.1.0 version (even after update repo, etc..)

**Comment by jadsonlourenco** [comment]
@havocked you need use from this repo, master branch, not using version number. I think.
`pod 'KDEAudioPlayer', :git => 'https://github.com/delannoyk/AudioPlayer.git', :branch => 'master`
