### ISSUE TITLE
How to know the player finished play current source

### ISSUE THREAD

**Issue by a1259667899** [delannoyk/AudioPlayer#135]

**Comment by jadsonlourenco** [comment]
* `audioPlayer(_ audioPlayer: AudioPlayer, willStartPlaying item: AudioItem)` If the player will start a new item, so, the current has finished.
* `audioPlayer.hasNext()` Indicate if has more items to play after the current source, on the queue.

**Comment by abacaj** [comment]
This is not an answer ^

There is no way to "react" to the audio player finishing. It means we have to poll the "hasNext" function.

Why is audio player finish event not exposed?: https://developer.apple.com/documentation/avfoundation/avaudioplayerdelegate/1389160-audioplayerdidfinishplaying

**Comment by abacaj** [comment]
@jadsonlourenco please see above comment

**Comment by abacaj** [comment]
correct solution is posted here: https://github.com/delannoyk/AudioPlayer/issues/149
