### ISSUE TITLE
Synchronize UI with player state

### ISSUE THREAD

**Issue by funkenstrahlen** [delannoyk/AudioPlayer#14]
I plan to integrate your player into my app. I am currently working on an app that does play podcast show livestreams.

I need to sync my UI with the player state. For example if the stream ends and no data is being received any more I need to update my UI. (there are of course a lot more cases to cover).

What's the best way being informed as a ViewController about the player state?

**Comment by delannoyk** [comment]
You can use the `delegate` property on your AudioPlayer instance and implement this function:
`func audioPlayer(audioPlayer: AudioPlayer, didChangeStateFrom from: AudioPlayerState, toState to: AudioPlayerState)`

**Comment by funkenstrahlen** [comment]
Thanks a lot for your quick response! The delegate is great!

However I do not know how to check for one case:

If I try to stream an AudioItem with an URL that does not stream any content the player stays in the state `buffering`. Shouldn't it move to `stopped`?

What happens if a stream ends? Will the player move to `buffering` and try to get more content? When will it "realize" there will be no more content and move to `stopped` or `failed` state?

**Comment by funkenstrahlen** [comment]
Maybe there should also be an .Error or .Failed state?

**Comment by delannoyk** [comment]
> If I try to stream an AudioItem with an URL that does not stream any content the player stays in the state buffering. Shouldn't it move to stopped?
> Maybe there should also be an .Error or .Failed state?

Yep, I do agree. I made it in [develop](https://github.com/delannoyk/AudioPlayer/tree/develop). Tell me what you think! :smile:

**Comment by funkenstrahlen** [comment]
The new .Failed state works great! Exactly as expected!

I am not quite sure what's happening now at the end of a livestream. Will it be .Failed or .Stopped? But that's a minor thing.

Thanks a lot for fixing so fast!

**Comment by delannoyk** [comment]
It should be `.Stopped` since AVPlayer will post an `AVPlayerItemDidPlayToEndTimeNotification`.
