### ISSUE TITLE
Propose Logo

### ISSUE THREAD

**Issue by mirzazulfan** [delannoyk/AudioPlayer#144]
Hi @delannoyk .. I'm graphic disigner. I would like to know if you are interested that I make a logo for your project? If you allowed me, i"ll make logo for your project and it's free.
Best Regard

**Comment by delannoyk** [comment]
Hey @mirzazulfan 
Thanks for the offer but I don't think you need to go through the hassle of creating a logo for this project. Appreciate it

**Comment by jadsonlourenco** [comment]
I think having a "logo" and a good presentation (read me docs) help a lot other developers.
Example: https://github.com/jadsonlourenco/react-native-shake-event
