### ISSUE TITLE
private func updateNowPlayingInfoCenter() should be public

### ISSUE THREAD

**Issue by funkenstrahlen** [delannoyk/AudioPlayer#15]
I have the following scenario:

I want to start playing a web audio livestream. Therefore I define the AudioItem and call the player to play it.

I also want to set an artwork image for the lockscreen. However this is an async network request. So currently if I want to set the artwork image and play the AudioItem I have to wait until the artwork request completed to start the player.

I would like to do the following:

```swift
        currentItem = AudioItem(mediumQualitySoundURL: event.streamurl)
        currentItem?.artist = event.podcastSlug
        currentItem?.title = event.title
        player.playItem(currentItem!)

        // fetch coverart from image cache and set it as lockscreen artwork
        Alamofire.request(.GET, event.imageurl)
            .responseImage { response in
                if let image = response.result.value {
                    self.currentItem?.artworkImage = image
                    self.player.updateNowPlayingInfoCenter()
                }
        }
```

However this is not possible as `updateNowPlayingInfoCenter()` is currently declared as private.

**Comment by delannoyk** [comment]
You don't need to call `updateNowPlayingInfoCenter()` because properties of the currentItem are observed within the player to change whenever you change it's property.
Doesn't it work? I haven't noticed bugs with that on my app.

**Comment by funkenstrahlen** [comment]
Oh that's even better! However currently it does not work yet but I think this another issue, because the MPRemoteCommand Center is not configured at all currently for me. No play/pause or title working.

**Comment by funkenstrahlen** [comment]
@delannoyk By the way: Really nice code! I am very happy and thankful you wrote that code. Makes my life a lot easier :heart:

**Comment by delannoyk** [comment]
Thanks man!
I'll look into your other issues later today and probably fix them in the evening if possible.
