### ISSUE TITLE
How to retrieve the player reference when implementing the Control Center / Lockscreen in AppDelegate?

### ISSUE THREAD

**Issue by wilbyang** [delannoyk/AudioPlayer#160]
How to retrieve the player reference when implementing the Control Center / Lockscreen in AppDelegate?

**Comment by danielmartinprieto** [comment]
Hi, @wilbyang.

You have several options, although none of them are strictly related to the `AudioPlayer` class, but the way you architecture your application. You could:
- Create the instance of the AudioPlayer class within the AppDelegate, so you can have a reference to it and use it when implementing the methods you need. Then you need to pass that instance to the rest of your program via dependency injection. **This is the recommended approach**.
- Put the `AudioPlayer` class into a singleton, so you can access it easily from wherever you want (note that this is not an approach people tend to like, but it can work for you if your application only uses one instance of the AudioPlayer class and you don't care a lot about unit tests.
- Use any other way to communicate your `AppDelegate` class and your instance of `AudioPlayer` without being explicitly connected, like the `NotificationCenter` class.
