### ISSUE TITLE
Configure buffer size?

### ISSUE THREAD

**Issue by funkenstrahlen** [delannoyk/AudioPlayer#17]
Is there a way to configure the buffer size?

There seems to be a way to do that with AVPlayer: http://stackoverflow.com/questions/21400591/buffer-size-for-avplayer-avplayeritem

**Comment by delannoyk** [comment]
There's no way right now with AudioPlayer. I'll look into that!

**Comment by funkenstrahlen** [comment]
That's not very urgent. Just a thought for bad network connections.

**Comment by delannoyk** [comment]
What would you use that for? Basically, it's just delaying the player from playing content. I don't see how that would really help bad connection but maybe I misunderstood your goal.

**Comment by funkenstrahlen** [comment]
I use AudioPlayer to play radio livestreams. So having a huge enough buffer in bad connection situations is important.

I know AVPlayer does not allow setting the buffer size explicitly. Therefore the only way is to delay the player because AVPlayer continues fetching the audio in the background, so the result is some cache time.

**Comment by samuelbeek** [comment]
I actually want to do the exact opposite. Tracks start playing when on avarage 900 seconds are loaded, which in my opinion is way too much.

**Comment by ddfreiling** [comment]
This should now be possible with:

AVPlayer.automaticallyWaitsToMinimizeStalling
https://developer.apple.com/reference/avfoundation/avplayer/1643482-automaticallywaitstominimizestal
AVPlayerItem.preferredBufferDuration
https://developer.apple.com/reference/avfoundation/avplayeritem/1643630-preferredforwardbufferduration

**Comment by delannoyk** [comment]
Feature is on master, thanks for @ddfreiling
