### ISSUE TITLE
Carthage error: SWIFT_VERSION '3.0' is unsupported

### ISSUE THREAD

**Issue by terryworona** [delannoyk/AudioPlayer#176]
Library looks great. 

Getting a Carthage error though. 

Cartfile:
```
github "delannoyk/AudioPlayer" 
```

Update:
```
$ carthage update AudioPlayer --platform iOS
```

*** ARCHIVE FAILED ***

<img width="1140" alt="Screen Shot 2020-04-21 at 10 12 59 PM" src="https://user-images.githubusercontent.com/358709/79943262-4d0f7c80-841d-11ea-9806-e64b54a6bcd8.png">

Any help would be appreciated. Thanks!

**Comment by terryworona** [comment]
I searched the project for `SWIFT_VERSION` but I couldn't find any evidence of `3.0` in any files.

**Comment by delannoyk** [comment]
Hey @terryworona.

You'll need to explicitly target master in your `Cartfile`: `github "delannoyk/AudioPlayer" "master"`.
I'm working on fixing a few of the issues that were reported and adding more tests but to be honest I'm a bit slow right now, but I'll do a release after that.

Hope that helps, let me know 🙂

**Comment by terryworona** [comment]
Awesome -- works now. 

I thought if you don't specify a branch in your `Cartfile` it will use the default branch associated with the Github repo -- is your default not `master`?

Anywho, thanks for the help. 

I forked your repo and added a (crude) fade in/out [feature](https://github.com/terryworona/AudioPlayer/commit/1b6a7e012b02d0a42c089dfd3b8409bc18457fea).

**Comment by delannoyk** [comment]
@terryworona by default Carthage picks up the latest release, not a branch
