### ISSUE TITLE
How to handle Remote Control events?

### ISSUE THREAD

**Issue by funkenstrahlen** [delannoyk/AudioPlayer#18]
I found

```
func remoteControlReceivedWithEvent(event: UIEvent) {}
```

in you code. However this function is not get called by default. What do I have to do to manage that?

Why do you not use MPRemoteCommandCenter

https://developer.apple.com/library/prerelease/ios/documentation/MediaPlayer/Reference/MPRemoteCommandCenter_Ref/index.html#//apple_ref/occ/instp/MPRemoteCommandCenter/pauseCommand

**Comment by delannoyk** [comment]
```swift
func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
    application.beginReceivingRemoteControlEvents()
}

//Then in your UIResponder (or app delegate if you will)
override func remoteControlReceivedWithEvent(event: UIEvent?) {
    if let event = event {
        yourPlayer.remoteControlReceivedWithEvent(event)
    }
}
```

**Comment by delannoyk** [comment]
> Why do you not use MPRemoteCommandCenter

I'll look into it later today.

**Comment by funkenstrahlen** [comment]
Thanks a lot! Maybe it makes sense to put that into the Readme too.

With MPRemoteCommandCenter you could register for the remote commands directly in your player code and the player users would not be required to put this code into their AppDelegate.

However it might be even better to leave it as it is now, because I now can decide if I want to use your handler or write my own.

Thanks for helping me!

**Comment by delannoyk** [comment]
> However it might be even better to leave it as it is now, because I now can decide if I want to use your handler or write my own.

That was intended even though I didn't know about `MPRemoteCommandCenter`.

> Thanks a lot! Maybe it makes sense to put that into the Readme too.

Yup, 't was in my TODO list :+1:
