### ISSUE TITLE
How to use AudioPlayerDelegate

### ISSUE THREAD

**Issue by Ravichandrane** [delannoyk/AudioPlayer#22]
Hi There ! 

I wondering how to use "AudioPlayerDelegate", I don't really understand how to use it do you have any exemple please :) 

I also want to know how to update the UISlider and get the AudioPlayer status if is playing or not. 

Thanks.

**Comment by delannoyk** [comment]
I updated the README with a bit more explanations. Could you check it out and let me know what are your questions ?

**Comment by Ravichandrane** [comment]
Hey thanks for your answer :) 

When I try to print the duration or the percentageRead nothing append... 
Can you show me with a exemple how to use the delegate please :) 

```swift
func audioPlayer(audioPlayer: AudioPlayer, didChangeStateFrom from: AudioPlayerState, toState to: AudioPlayerState) {
        
    }
    
func audioPlayer(audioPlayer: AudioPlayer, didFindDuration duration: NSTimeInterval, forItem item: AudioItem) {
        print(duration)
    }
    
func audioPlayer(audioPlayer: AudioPlayer, willStartPlayingItem item: AudioItem) {
        print(item)
    }

func audioPlayer(audioPlayer: AudioPlayer, didUpdateProgressionToTime time: NSTimeInterval, percentageRead: Float) {
        print(percentageRead)
    }
```

**Comment by delannoyk** [comment]
Hi @Ravichandrane 
Did you try setting breakpoints in any of the methods? Because duration should be called...
Regarding that, how are you using AudioPlayer?

**Comment by Ravichandrane** [comment]
Hi @delannoyk, 

I want the music continue to play when I dismiss the player view so I create a singleton and call AudioPlayer inside the singleton after that I use the singleton in my player view controller. 

```swift
// Singleton

import UIKit
import KDEAudioPlayer

class MusicPlayer: NSObject {
    
    static let shareInstance = MusicPlayer()
    static let player = AudioPlayer()
    static var isPlaying: Bool = true
    
    static func playItemWithUrl(url: NSURL) {
        let item = AudioItem(highQualitySoundURL: url, mediumQualitySoundURL: nil, lowQualitySoundURL: nil)
        player.playItem(item!)
    }
    
    static func play() {
        player.resume()
        isPlaying = true
    }
    
    static func pause() {
        player.pause()
        isPlaying = false
    }
    
    static func stop() {
        player.stop()
    }
    
    static func nowPlayingInfoContent(title: String, artist: String, artwork: NSData) {
        player.currentItem?.title = title
        player.currentItem?.artist = artist
        player.currentItem?.artworkImage = UIImage(data: artwork)
    }
}
```
```swift
// PlayerViewController

func prepareAudio() {
  MusicPlayer.playItemWithUrl(NSURL(string: songUrl)!)
}
```

**Comment by delannoyk** [comment]
Seems to me like you forgot `player.delegate = self`

**Comment by Ravichandrane** [comment]
Ah... I forgot to specify the delegate my bad... Thanks @delannoyk :D :+1:

**Comment by jusonqiu** [comment]
when i add the player.delegate = self, will show error like "Cannot assign value of type viewcontroller to type "AudioPlayerDelegate?"
