### ISSUE TITLE
It does not trigger the StateChanged

### ISSUE THREAD

**Issue by ahpiau18** [delannoyk/AudioPlayer#27]
i try the following code, and it doesn't print the State, did i missed anything? 

var player = AudioPlayer()
let item = AudioItem(highQualitySoundURL: playerURL)
player.playItem(item!)

//not working or i missed something
func audioPlayer(audioPlayer: AudioPlayer, didChangeStateFrom: AudioPlayerState, toState: AudioPlayerState) {
        if (toState == AudioPlayerState.Buffering) {
            print("Bufferring")
        } else if (toState == AudioPlayerState.Paused){
            print("Pause")
        } else if (toState == AudioPlayerState.Paused){
            print("Pause")
        } else if (toState == AudioPlayerState.Playing){
            print("Playing")
        } else if (toState == AudioPlayerState.Stopped){
            print("Stopped")
        } else if (toState == AudioPlayerState.WaitingForConnection){
            print("WaitingForConnection")
        }
    }

**Comment by delannoyk** [comment]
Hi,
Probably yes.

1/ I don't see setting the delegate property of your audioPlayer. Do you?
2/ Be sure to *keep a reference* to your audioPlayer because if you just allocate it and play an item without keeping the reference, it will get deallocated right away.

**Comment by delannoyk** [comment]
Let me know :)

**Comment by ahpiau18** [comment]
hey @delannoyk 

after added the delagete property, it works like charm.
:)
Thanks
