### ISSUE TITLE
Next or Previous action freeze 

### ISSUE THREAD

**Issue by Ravichandrane** [delannoyk/AudioPlayer#28]
Hi There ! 

I noticed a bug, only on iPhone not on the simulateur, when I press next or previous action the music freeze 2ms and play the next track. It's normal ? 

Thanks.

**Comment by delannoyk** [comment]
Hi!
Hard to tell. First, what do you mean by "freeze"?
If you change the current item by doing `next()` or `previous()` (or more generally change the current item), the player will buffer data first.

**Comment by Ravichandrane** [comment]
Hi Thanks for your reply. 

Meaning when I press next() or previous() the current track freeze 2ms like old mp3 cassette, I think it's happen during the buffering. It's possible to load the next track in background when the current track is playing ?

**Comment by delannoyk** [comment]
Yes it's probably buffering then.
I'm not planning to offer this kind of feature since probably a lot of people wouldn't need it - and it seems like a lot of work.

**Comment by Ravichandrane** [comment]
Okay I'm gonna work on my side and push in a new branch :) 

Thanks again, 
Have a nice day.

**Comment by delannoyk** [comment]
I'm curious how you plan to do it. Could you let me know if/when you finish it so I can have a look?
Have a nice day too!

**Comment by Ravichandrane** [comment]
Yeah sure, I fork your project so when I finish this feature I will create a new feature branch and push on it :)
