### ISSUE TITLE
Audio ID3 information not being pulled

### ISSUE THREAD

**Issue by han9over** [delannoyk/AudioPlayer#35]
I'm not sure if this is issue with the file I have, but I tried to host a MP3 file remotely with all the ID3 information on it. I'm also not sure if I need to do something for the player to pull that information, but I don't see that being pulled and the observer getting fired.

Can you please direct me in right path?

Thanks in advance.

**Comment by delannoyk** [comment]
It's not possible right now but it sounds like a great addition! I'll look into that!

**Comment by han9over** [comment]
@delannoyk Great. Thank you. I'm wondering how are the title, artist, album etc populated in AudioItem. I also saw a KVO and addition of observer for those. Sorry, I'm a bit new to swift, tried to figure out myself but was unable to.

**Comment by delannoyk** [comment]
On the current version, you have to populate it yourself. And KVO on those trigger changes for MPNowPlayingInfoCenter.

**Comment by han9over** [comment]
@delannoyk Understood. Thank you. Temporarily, I can pull that information using AVMetadata for testing purposes.

**Comment by delannoyk** [comment]
Hi @han9over 

I added this feature on `develop` branch.
The `AudioItem` will take care of the metadata parsing. Also if you want to customise it, you can subclass `AudioItem`.

Let me know if you have any comment/suggestion.

**Comment by han9over** [comment]
Thanks a lot. I will try it out.

**Comment by delannoyk** [comment]
Actually, I'll leave this open cause I'd like to have some sort of callback when it's set, and I'm not sure if live streams can have metadata. Still have to look up for that.

**Comment by funkenstrahlen** [comment]
Have not tested this, but how does this work together with manually setting metadata to `AudioItem`? Which one has priority? Or do I have to enable automatic metadata fetching?

**Comment by delannoyk** [comment]
It'll set properties only if their nil (and found in metadata).

**Comment by funkenstrahlen** [comment]
That sounds like a good solution!

**Comment by delannoyk** [comment]
Seems like neither of SHOUTcast and Icecast give ID3 data. [Source](http://stackoverflow.com/a/6049953/1018794).

**Comment by delannoyk** [comment]
Ok, I tested it with an Icecast stream and it doesn't seem to contain any metadata. Anyway, if by any chance it would for another server, parsing would still get called.
Closing this and I'll be merging into `master` a bit later today.

**Comment by han9over** [comment]
Awesome. You rock @delannoyk
