### ISSUE TITLE
AudioPlayer is skipping through playlist on error response

### ISSUE THREAD

**Issue by MattesGroeger** [delannoyk/AudioPlayer#42]
I'm currently investigating the issue that the player is skipping through the playlist when it reaches the maximum retries per item (because of a backend error). I'd like to have it just stopping/pausing at the current item with the error state and have the user deciding to try the next item in the queue.

I could patch it myself but I'm wondering what the best approach would be. Maybe I'm also missing something? Hope you can help out here. I really like the implementation and API, good work!

**Comment by delannoyk** [comment]
Yup, I see your point and I totally agree that the player should not decide how to behave on error.
I didn't think of that when developing that feature.

Anyway, 4e1d49d3ad4835560dc2b53488d2a40c54e9d971 fixed this and I'm going to tag this release as 0.8.0 as it's a change that affects everyone, even if it's for the best.

**Comment by delannoyk** [comment]
Just so you know, you should tell how the player to behave when the delegate to alert status changed is called with `toState` being `.Failed`.

**Comment by MattesGroeger** [comment]
Nice. I like your solution. Will give it a try later. Thanks a lot, much appreciated!

**Comment by MattesGroeger** [comment]
I just tried it but it still skips to the next one.

I don't do anything in the `didChangeStateFrom` delegate on `.MaximumRetryCountHit` as I just want it to stay in this state.

When I put in an `audioPlayer.pause()` it continues to call `.MaximumRetryCountHit` for the same item. Also the app get's stalled during the retry but that's probably a different issue.

Any idea?

**Comment by delannoyk** [comment]
That's pretty weird but maybe I don't understand your issue.

I tried setting a wrong URL to 5 items that I queued up (title are "0", "2", "3", "4" & "4"):
```
Queue (item.title): ["0", "1", "2", "3", "4"]
State: Buffering
WillStartPlaying: Optional("0")
Failed(KDEAudioPlayer.AudioPlayerError.FoundationError(Optional(Error Domain=NSURLErrorDomain Code=-1100 "The requested URL was not found on this server." UserInfo={NSLocalizedDescription=The requested URL was not found on this server., NSUnderlyingError=0x7fadab4f4920 {Error Domain=NSOSStatusErrorDomain Code=-12938 "(null)"}})))
```
That's it, the player waits.

**Comment by MattesGroeger** [comment]
Maybe the difference here is that I break it during playback. I have items queued up and playing and during playback I enable geoblocking which leads to a bad-gateway response.
