### ISSUE TITLE
play progress event is delayed util buffer is done

### ISSUE THREAD

**Issue by jjhlzn** [delannoyk/AudioPlayer#46]
when network is net so good, loading audio is not so fast. And, I found play progress event is delayed util buffer is done. 
I add some log code to AudioPlayerDelegate, the following is log:

> duration = 332.355918367347
> audioPlayer:didLoadRange, loadRange = (0.0, 28.003265306122447)
> audioPlayer:didLoadRange, loadRange = (0.0, 62.798367346938775)
> audioPlayer:didLoadRange, loadRange = (0.0, 97.619591836734699)
> audioPlayer:didLoadRange, loadRange = (0.0, 130.45551020408163)
> audioPlayer:didLoadRange, loadRange = (0.0, 163.42204081632653)
> audioPlayer:didLoadRange, loadRange = (0.0, 196.33632653061224)
> audioPlayer:didLoadRange, loadRange = (0.0, 229.35510204081632)
> audioPlayer:didLoadRange, loadRange = (0.0, 262.19102040816324)
> audioPlayer:didLoadRange, loadRange = (0.0, 295.02693877551019)
> audioPlayer:didLoadRange, loadRange = (0.0, 332.35591836734693)
> audioPlayer:didUpdateProgressionToTime called, progressPercentage = 2.40773
> audioPlayer:didUpdateProgressionToTime called, progressPercentage = 2.55786
> audioPlayer:didUpdateProgressionToTime called, progressPercentage = 2.70847
> audioPlayer:didUpdateProgressionToTime called, progressPercentage = 2.85875
> audioPlayer:didUpdateProgressionToTime called, progressPercentage = 3.0096
> audioPlayer:didUpdateProgressionToTime called, progressPercentage = 3.15962
> audioPlayer:didUpdateProgressionToTime called, progressPercentage = 3.31018
> audioPlayer:didUpdateProgressionToTime called, progressPercentage = 3.46054

**Comment by delannoyk** [comment]
Hi,
I'm not observing this on my item. Tried with a livestream URL and with a MP3 hosted only.
Would you mind sharing your item URL so that I can reproduce it?
Thanks

**Comment by jjhlzn** [comment]
yes, http://jjhaudio.hengdianworld.com/songs/houlai.mp3.  it's from china.

**Comment by delannoyk** [comment]
Yup thank you for reporting this, it was introduced by myself on `0.8.3` and is ok with new `0.8.4`.

**Comment by jjhlzn** [comment]
thanks.
I have fetched the latest code, and the issue is gone.
