### ISSUE TITLE
When time is not seekable, I think just seek as late as possible is not reasonable.

### ISSUE THREAD

**Issue by jjhlzn** [delannoyk/AudioPlayer#48]
When time is not seekable, just seek as late as possible or as early as possible is not reasonable.
I think player should pause utils the time is seekable after some time buffering. And player resume play.
@delannoyk, what do you think?

**Comment by delannoyk** [comment]
Yep I do agree, a PR is currently in progress for this: #41.
Feel free to give your opinion there.

**Comment by delannoyk** [comment]
Fixed with PR #52
