### ISSUE TITLE
No `Podfile' found in the project directory.

### ISSUE THREAD

**Issue by jusonqiu** [delannoyk/AudioPlayer#51]

**Comment by delannoyk** [comment]
Probably because your Podfile doesn't exist in the directory you try to enter `pod install`. Anyway, this is related to CocoaPods, not to this project.

**Comment by jusonqiu** [comment]
But your project doesen't exist Podfile

**Comment by delannoyk** [comment]
Indeed, there is no Podfile in this repo. Why is this an issue to you?

**Comment by jusonqiu** [comment]
Is this just the library ,can not run like app?

**Comment by delannoyk** [comment]
Yep it's just a library, there is no app!
What got you confused thinking it was an app? Maybe I can change some things in the README.
