### ISSUE TITLE
How to use     let deleglate : AudioPlayerDelegate = self

### ISSUE THREAD

**Issue by jusonqiu** [delannoyk/AudioPlayer#55]
show error 

value of type viewcontroller does not conform to specified type "AudioPlayerDelegate"

**Comment by delannoyk** [comment]
Your `ViewController` should implement methods defined in `AudioPlayerDelegate`. Also, it should explicitly conform to it like this:

```swift
class ViewController: UIViewController, AudioPlayerDelegate {
    //TODO: implement methods defined in AudioPlayerDelegate.
}
```
