### ISSUE TITLE
deinit doesn't remove the kvo observers

### ISSUE THREAD

**Issue by arun057** [delannoyk/AudioPlayer#6]
I ended monkey patching the deinit() function with this 

```
    deinit {
        self.desub()
        
        reachability.stopNotifier()
        unobserve(ReachabilityChangedNotification, object: reachability)

        qualityAdjustmentTimer?.invalidate()
        qualityAdjustmentTimer = nil

        retryTimer?.invalidate()
        retryTimer = nil

        currentItem = nil
        enqueuedItems = nil
        player = nil

        endBackgroundTask()
    }
    
    private func desub() {
        for keyPath in AVPlayer.ap_KVOItems {
            player?.removeObserver(self, forKeyPath: keyPath)
        }
    }

```

**Comment by delannoyk** [comment]
You're right! Working on a fix right now.

**Comment by delannoyk** [comment]
@arun057 
Setting these to nil in `deinit`:
```swift
currentItem = nil
enqueuedItems = nil
player = nil
```
didn't call their didSet while doing it in `stop()` works like a charm.

Fixed in 0.2.6 dd58037d7a7e922a3d79f439ed1bbdb0cd762023

**Comment by arun057** [comment]
Will test and report back

**Comment by arun057** [comment]
I was calling stop and changing mp3s when this happened, so not sure if this is the definite fix ( either way will test and report back )

**Comment by delannoyk** [comment]
Hi!
Based on my tests it worked pretty well like this. Please let me know if you face any issues, I'd be glad to help. In the meantime, I'll keep this issues closed and reopen if that doesn't fix your problem.

**Comment by arun057** [comment]
tested, looks good :) thank you very much

**Comment by delannoyk** [comment]
:+1:
