### ISSUE TITLE
Use of Undeclared type 'TimeRange'

### ISSUE THREAD

**Issue by colonelsshanslanda** [delannoyk/AudioPlayer#64]
`func audioPlayer(audioPlayer: AudioPlayer, didLoadRange range: TimeRange, forItem item: AudioItem) {
        
    }`

This delegate method has a TimeRange type. Not sure what is the datatype to be declared in the ViewController.

**Comment by delannoyk** [comment]
You should use `AudioPlayer.TimeRange`
