### ISSUE TITLE
Sound with echo

### ISSUE THREAD

**Issue by jkdntc** [delannoyk/AudioPlayer#65]
The problem is when I play the voices messages on the slow mode, it will have echo and breaking up problem. It works fine for the normal speed and fast speed.

I set rate ＝ 0.7 then sound with echo.

example: [http://api.breadenglish.com/app/139.mp3](url)

**Comment by delannoyk** [comment]
Hi,

Could you provide an example sound so that I can test it and see what I can do to help? This is obviously related to `AVPlayer` and I'm not sure that there's anything I can do.
