### ISSUE TITLE
func audioSessionGotInterrupted problem?

### ISSUE THREAD

**Issue by jkdntc** [delannoyk/AudioPlayer#66]
When I play the voice messages in the App, it works fine. However, if I switch to another Apps to play videos and then switch back again, I could not continue to play the voice messages no matter how. Even I tap on the messages, it won’t work either. 

My solution: 
add pausedForInterruption = false when set currentItem

**Comment by delannoyk** [comment]
Hi @jkdntc 
Is this still an issue on the latest version?

**Comment by magorik** [comment]
add pausedForInterruption = false when set currentItem
Its work for me.

**Comment by danielmartinprieto** [comment]
Hey, @delannoyk. Just saw in one of my apps a bug related with this issue. I will try tomorrow the fix in this [PR](https://github.com/ddfreiling/AudioPlayer/commit/d96bb5cd8ee80b0947bd9f34c3ac18ffa3906ca0) to test if it works. Have you been able to take a look at the code?

**Comment by danielmartinprieto** [comment]
I can confirm that the work in https://github.com/delannoyk/AudioPlayer/pull/115 by @ddfreiling fixes this issue. Thanks, @ddfreiling! I will post some comments in the PR, and it'd be great if @delannoyk gives his input as well before merging.
