### ISSUE TITLE
Use in Objective C project

### ISSUE THREAD

**Issue by eiros** [delannoyk/AudioPlayer#67]
Hi there! I have problems with using the delegate.
I added "use_frameworks!" in my pod file and imported library "@import KDEAudioPlayer;"
When I added property "@property (strong, nonatomic) AudioPlayer *internalPlayer;"
And it was OK.
I can use AudioPlayer methods such as "playItem" or "removeItemAtIndex" and so on, but with delegate a have an error "Cannot find protocol declaration for 'AudioPlayerDelegate'".
Maybe I did something wrong?
![2016-08-06 1 45 18](https://cloud.githubusercontent.com/assets/9737848/17450040/e7906212-5b7f-11e6-90b3-7bcd05a59ddf.png)

**Comment by delannoyk** [comment]
Hi,

I haven't really tested the integration of this lib in an Objective-C project.
This error seems to be related to the `AudioPlayerDelegate` that is not obj-c compatible. I'll see what I can do.

Keep you posted.

**Comment by eiros** [comment]
Thank you! I am looking forward to news

**Comment by eiros** [comment]
Hi! Are there any changes?

**Comment by delannoyk** [comment]
Hi!
This is on the TODO list but I still haven't work on that yet. Thing is some types currently used are not objc compatible so some one them require full re-work.
