### ISSUE TITLE
Control center events not working

### ISSUE THREAD

**Issue by senthilsivanath** [delannoyk/AudioPlayer#68]
Added beginReceivingRemoteControlEvents to my view controller. On click of control center events, i am getting debugging points hit in remoteControlReceivedWithEvent method, but the music is not pause / resume / forwarded / rewinded. 

AudioPlayer does not affect the music.

**Comment by delannoyk** [comment]
Hi, do you forward calls to the audio player ?

**Comment by senthilsivanath** [comment]
was delegating to wrong instance of AudioPlayer, Made AudioPlayer as static (shared). Control center events are working fine.
