### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by lfarah** [delannoyk/AudioPlayer#70]
Hey, I'd love to see this lib available in Swift 3 so I can implement it in my project.

Thanks 😄

**Comment by delannoyk** [comment]
Hi Lucas!

It's coming, but I don't have a lot of time right now - moving from Europe to Canada in 2 weeks so... yeah, it's complicated.
I'll do my best to update it before but I can't give you an ETA yet.

**Comment by jookes** [comment]
It seems that this repo added swift3 support
https://github.com/bartleby/AudioPlayer

**Comment by samuelbeek** [comment]
@delannoyk when you have the time? Can you take a look at this branch? https://github.com/bartleby/AudioPlayer. I've used it in my project and it's a perfect Swift 3 migration of your repo.

**Comment by davidseek** [comment]
+1

**Comment by lopify** [comment]
+1

**Comment by delannoyk** [comment]
`master` is currently usable with swift 3.0. I still have some tests to run before releasing it to CocoaPods.
In the meantime, feel free to test it an report issues if you want to!

**Comment by asidarous** [comment]
Hello, how do we use it without cocoapods?

**Comment by RubenMH** [comment]
Hi @delannoyk 

Could you upgrade the version of master with swift 3.0 to CocoaPods?

Thanks!

**Comment by delannoyk** [comment]
Hey everyone,

Just published `1.1.0-beta`. The version is marked as beta as there is still one bug I have to investigate. Closing this issue though.
