### ISSUE TITLE
Does Control Centre still work even after you launch another app?

### ISSUE THREAD

**Issue by anasqadrei** [delannoyk/AudioPlayer#71]
Control Center/Remote Control works fine in Home screen or Lock screen. But once I go and launch another app such as Settings for example, the Control Center stops working. If I go to Home again, it won't work. I have to launch my audio app first then it will work.

Is it suppose to do that? Is it a bug? Why doesn't it work like the Apple Music app where control centre works even if you launch other apps?

**Comment by anasqadrei** [comment]
Hey @delannoyk have you had a chance to look it at?

**Comment by delannoyk** [comment]
Hi!
Sorry for the delay, for the next month I won't have a lot of time to handle issues/migrations/releases.
Anyway, this behaviour is not intended. Could you show me how/where you handle the remote events?

**Comment by anasqadrei** [comment]
I've created a single view app with the below code. Remote control works fine if I exit the app to the Home screen. But once I open any other app such as Settings, for example, remote control stops working until I re-open the KDEAudioPlayer app.

Is anyone able to support this while you're away?

**ViewController.swift:**
```
import UIKit
import KDEAudioPlayer

class ViewController: UIViewController, AudioPlayerDelegate {
    
    let audioPlayer = AudioPlayer()

    override func viewDidLoad() {
        super.viewDidLoad()

        self.audioPlayer.delegate = self
        
        let NSSongURL = NSURL(fileURLWithPath: NSBundle.mainBundle().pathForResource("Hellberg ft. Jessarae - Wasted Summer.mp3", ofType:nil)!)        
        let item = AudioItem(mediumQualitySoundURL: NSSongURL)
        self.audioPlayer.playItem(item!)
    }
    
    override func viewDidAppear(animated: Bool) {
        self.becomeFirstResponder()
    }
    
    override func canBecomeFirstResponder() -> Bool {
        return true
    }

    override func remoteControlReceivedWithEvent(event: UIEvent?) {
        if let event = event {
            self.audioPlayer.remoteControlReceivedWithEvent(event)
        }
    }
    
}
```

**AppDelegate.swift:**
```
import UIKit

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?

    func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
        // Override point for customization after application launch.
        application.beginReceivingRemoteControlEvents()
        return true
    }
}
```

**Comment by delannoyk** [comment]
Just tried with the exact same code, I'm not seeing any issues. Did you enable the audio background mode for your app?

**Comment by anasqadrei** [comment]
Yup, that solved it only on the physical iPhone device. Simulator still has the same issue. Did you run the code on the simulator or on the device?

**Comment by delannoyk** [comment]
Device. Can I close this?

**Comment by anasqadrei** [comment]
Sure, I'll do it for you. Thanks for the help :)
