### ISSUE TITLE
Volume Control

### ISSUE THREAD

**Issue by anasqadrei** [delannoyk/AudioPlayer#72]
I've noticed that `kdeAudioPlayer.volume` doesn't react to the iPhone device volume change.

`kdeAudioPlayer.volume` always starts with 1.0 even if the device's volume is 0.6 or 0.4 or whatever.

Also changing the volume on the device doesn't trigger a remote control event.

I know you're busy at the time, but I would love to have more powerful volume control feature whenever you're free.

**Comment by delannoyk** [comment]
This property doesn't represent the device volume but the player volume. If you want to check the device volume, I think `AVAudioSession.sharedInstance().outputVolume` is the way to go.
