### ISSUE TITLE
Working with swift 2.3

### ISSUE THREAD

**Issue by mhmmdmz** [delannoyk/AudioPlayer#78]
Hi, 

I wanted to keep the version of KDEAudioPlayer that I have on my project to work with swift 2.3 only. However, it seems I mistakenly upgraded it with the master branch that works with swift 3 - result is that the compiler doesn't allow a project complied in 3.0.1 (i.e. KDE) with my existing project, which is in 2.3. 

Is there a way that I can get the 2.3 version of the code?

Thanks.

**Comment by delannoyk** [comment]
Hi,
Yes, using the `0.9.1` version should work for you.
So that should look like this in your `Podfile`:`pod 'KDEAudioPlayer', '= 1.0'`

**Comment by mhmmdmz** [comment]
Hi,

0.9.1 doesn't work. my compiler says that it was compiled in swift 3.0.1 so
I can't import it in 2.3 - I tried to set legacy as Yes ... but that throws
a lot of errors (setting legacy as No - compiles though)

**Comment by delannoyk** [comment]
This is weird because 0.9.1 shouldn't compile with swift 3. Can I ask you a screenshot of the source files you have for the pod, to ensure you're actually using 0.9.1?

**Comment by mhmmdmz** [comment]
I'm away from my screen at the moment but I'm sure it's 0.9.1 Cuz the
terminal too says so when I do a pod update
