### ISSUE TITLE
Player takes a while to start

### ISSUE THREAD

**Issue by mhmmdmz** [delannoyk/AudioPlayer#79]
I'm trying to stream audio from a server and your player has been a great blessing in that direction. It used to work great before I tried to implement a singleton. Now, when the singleton works, the player takes a long time to start... say about 30 seconds. I noticed in this duration, the control centre receives audio and stops many times (about 14) before finally deciding to play the audio. So it will start the timeline (only in the control centre) and go up to 4-6 seconds then collapse to 0 only to again repeat this ... till it finally plays. 

Is there a solution to this?

**Comment by delannoyk** [comment]
Mh this is weird. Care to share some code? My email is my github handle @gmail dot com.

**Comment by mhmmdmz** [comment]
Sent you the files via email.

**Comment by delannoyk** [comment]
I didn't receive anything.

**Comment by mhmmdmz** [comment]
delannoy@gmail.com - that's your id?

**Comment by delannoyk** [comment]
You forgot a 'k' there :)

**Comment by mhmmdmz** [comment]
Woops... Sent it again

**Comment by delannoyk** [comment]
On my test app It ran just fine so my guess is it's server or internet connection related so nothing I can do to help, sorry :(

**Comment by mhmmdmz** [comment]
Did you try the same links I shared? And encountered the issue?
