### ISSUE TITLE
Can add a option for caching audio file when playing ?

### ISSUE THREAD

**Issue by sayiwen** [delannoyk/AudioPlayer#8]
I want to cache audio file when playing . Any idea?

**Comment by delannoyk** [comment]
I agree that would be useful. I'll check how to do it the most efficient way and keep you posted.

**Comment by sayiwen** [comment]
I am wating...

**Comment by delannoyk** [comment]
Quick update: I've been working on it and it'll be available soon! 🙂

**Comment by funkenstrahlen** [comment]
Won't this change the foundation of the player a lot as this is not supported by the AVPlayer class of Apple? This might add a lot of complexity...

**Comment by delannoyk** [comment]
I've got a working tree in [feature/caching](https://github.com/delannoyk/AudioPlayer/tree/feature/caching). I'll do more test tomorrow with it.
Let me know what you guys think!

**Comment by delannoyk** [comment]
It currently has some bugs with queues when loading next song while current one hasn't finish loading (no error sent to delegate, ...). Working on that tonight.

**Comment by sayiwen** [comment]
Hi guy , this [article!](http://leshkoapps.com/wordpress/audio-streaming-and-caching-in-ios-using-avassetresourceloader-and-avplayer/) may be help you . But I can't understood it  .

**Comment by delannoyk** [comment]
Yep, but it's already implemented :) still have some bugs to work on but core feature is available.

**Comment by delannoyk** [comment]
It doesn't seem that there is a high demand for this feature while it requires a lot of work - and even the in-progress branch should be re-written to swift 3. Closing this but if you want I'm accepting a PR for this.

**Comment by yeralin** [comment]
Hey @delannoyk did you figure this out?

I tried it myself: https://stackoverflow.com/questions/45786283/avurlasset-when-response-doesnt-have-content-lenght-header

But I faced a problem, if server doesn't send 'Content-Length' my ResourceLoaderDelegate won't play the file.

**Comment by jadsonlourenco** [comment]
@yeralin I'm using this: https://github.com/r-plus/HLSion

**Comment by yeralin** [comment]
@delannoyk The problem here, I want to download song while it is being played. In your solution, I need to download song first, that is not what I need :/

The only way to do that is to implement custom ResourceLoaderDelegate, and I did it. It is working, but the only problem I currently have is playing audio stream w/o 'Content-Length' header.

**Comment by delannoyk** [comment]
@yeralin I'm not the one who suggested that library (@jadsonlourenco is) but I agree it has nothing to do with audio, it's just a layer over a network request.
Anyway. I think the branch with the resource loader still exists though it contains a few bugs https://github.com/delannoyk/AudioPlayer/tree/feature/caching
