### ISSUE TITLE
AudioPlayerDelegate doesn't get called with time updates playing a live stream

### ISSUE THREAD

**Issue by danielmartinprieto** [delannoyk/AudioPlayer#80]
Hi.

I've observed that `audioPlayer(_ audioPlayer: AudioPlayer, didUpdateProgressionTo time: TimeInterval, percentageRead: Float)` doesn't get called while playing a live stream. I've checked the code and it's because the player cannot know the total duration, therefore it skips calling the delegate.

In my opinion, this callback is still useful even if you don't know the total duration of the stream. For instance, for a given live stream we know which song is being played at a certain moment, if we can know when the stream started and the progression so far. But maybe there is another, easier way to accomplish this?

What do you think? Thanks.

**Comment by delannoyk** [comment]
Hi Daniel,
Correct me if I'm wrong but I think the `time` is only relative to when the user started playing the livestream isn't that right? I mean at the time he presses "Play" the time is 0, after 10 secs it's 10 etc etc. How would you know what is being played based on this relative time?

**Comment by danielmartinprieto** [comment]
Yes, I think that's correct.

Although you could know what's being played if you save the starting date (when the user presses play) and track the progress. This is useful as well if you want to seek back to a certain time, because if it's later than when you started, you already have the new _current_ date just adding the progress.

Another approach I wanted to follow is to get the timed metadata from the stream and call the backend with that info to know the data of the whole item, that's why I added the other PR that you already merged.

But in any case I think it's a nice feature to be able to track the progress of a stream, and right now that's not possible if it doesn't have a duration.

BTW, love the new structure of the code, it's so easy to go through it and make changes, congrats 💯

**Comment by delannoyk** [comment]
Makes sense. Working on that right now.
