### ISSUE TITLE
Observing AVAudioSessionInterruption doesn't work

### ISSUE THREAD

**Issue by danielmartinprieto** [delannoyk/AudioPlayer#83]
Hi.

I was just testing interruptions (triggering Siri, for example) and realised the method `audioSessionGotInterrupted(note: NSNotification)` was not being called. Checking the code I've seen the observer was being added passing it the AVPlayer instance, and afaik it's not AVPlayer which sends the AVAudioSessionInterruption notification. Just passing `nil` to the `object` parameter makes it work.
```
center.addObserver(self, selector: .audioSessionInterrupted, name: .AVAudioSessionInterruption, object: nil)
```
From the docs: 
> The object whose notifications the observer wants to receive; that is, only notifications sent by this sender are delivered to the observer.
If you pass nil, the notification center doesn’t use a notification’s sender to decide whether to deliver it to the observer.

As this was already implemented, I guess you tested it and it was working, so maybe I'm doing something wrong or I didn't get anything right?

**Comment by delannoyk** [comment]
No actually that's an error that slipped in when refactoring the project. Good catch!
I'm sorry about those kind of issues, as the main app I use this project on is not Swift 3 converted yet, I haven't detected those yet and that mainly the reason why I didn't release a new version of the pod yet.
Updating it right now!

**Comment by delannoyk** [comment]
Actually none of the notification were correct since they're not related to the player but to the audio session.
Fixed.
