### ISSUE TITLE
Missing AudioItem unique identifier

### ISSUE THREAD

**Issue by danielmartinprieto** [delannoyk/AudioPlayer#84]
Hi. It seems I'm bothering you a lot this week, sorry about that. I got very excited when I saw you refactored the framework and put more time into it, I thought I could use it in my projects (I already use it in production in a small tvOS app) and get more involved.

Anyway, I think it could be useful to have something like a unique identifier for the AudioItem object, to easily identify them without needing to hold a reference of the whole list, which seems more like an implementation detail. For instance, as I create my audio items with only one URL, I use it currently as an identifier.

**Comment by delannoyk** [comment]
Not bothering at all, that how we make this library better right?
I did think about putting a `userInfo` dictionary. What do you think about it?

**Comment by danielmartinprieto** [comment]
Mmm, that could work, you mean a custom dictionary where the library user can put any information, right? I was thinking in a simpler solution, more like a new `String` property on the `AudioItem` object, `identifier` or something like that, so you can look up easily in your data source for the element(s) associated with a certain audio item, but probably your suggestion is more powerful?

**Comment by delannoyk** [comment]
Actually, I've been wondering if this was really needed on the library. An `AudioItem` is an open class so it can be subclassed and you can add any property you want.
