### ISSUE TITLE
MPMediaItemArtwork deprecated

### ISSUE THREAD

**Issue by JeanetteMueller** [delannoyk/AudioPlayer#88]
it would be great to use an MPMediaItemArtwork as .artworkImage on AudioItem

Since MPMediaItemArtwork(image: UIImage) is deprecated you have to use something like this

MPMediaItemArtwork.init(boundsSize: CGSize.init(width: 512, height: 512) , requestHandler: { (size) -> UIImage in{
return UIImage.init(named: "artwork")
})

**Comment by delannoyk** [comment]
Hey @JeanetteMueller 
I added a new property `artwork` that is a MPMediaItemArtwork for your advance usage. Let me know if that works our for you!

**Comment by JeanetteMueller** [comment]
Great, thanks a lot
