### ISSUE TITLE
Information on change AudioItem

### ISSUE THREAD

**Issue by JeanetteMueller** [delannoyk/AudioPlayer#90]
When you switch from one AudioItem to another, the Audio Player State changes from .playing to .buffering. 

Would it be possible to get between an information the audioItem paused?

I want to save the current position but on buffering it is to late and there is no information what the last AudioItem was if i don't use  your playlist functionality.

**Comment by delannoyk** [comment]
Hey Jeanette,
Sorry for the delay.
If you manage your own queue, couldn't you just save the time before moving onto the next item?
