### ISSUE TITLE
Example Project

### ISSUE THREAD

**Issue by ilesmana** [delannoyk/AudioPlayer#93]
Hello,

Can you give an example project? I have implemented this with Swift 3, but it didn't work, the sound never played.

Here is my code:
let fileURL = NSURL(string: "this is my mp3 file url")
let player = AudioPlayer()
let item = AudioItem(mediumQualitySoundURL: fileURL as URL?)
player.play(item: item!)

Thank you

**Comment by delannoyk** [comment]
Hi,

Yes it's in my TODO list.
For your specific issue, you should retain your `AudioPlayer` instance or it will get deallocated right away.

**Comment by ilesmana** [comment]
Hi,

It's work!
thanks for your help. Sample project will be helpful.
