### ISSUE TITLE
Quicker update of audio progress on delegate

### ISSUE THREAD

**Issue by vaderdan** [delannoyk/AudioPlayer#94]
Hi 

I want to update audio progress when I'm playing sound. Now when I'm updating via the delegate
it works and updates it with rate of 0.5 second which is not very smoothly

can you make a config property on player object so I could modify it easily
see this

https://github.com/delannoyk/AudioPlayer/blob/master/AudioPlayer/AudioPlayer/event/PlayerEventProducer.swift#L138

**Comment by delannoyk** [comment]
@vaderdan I think it's kind of smooth enough. How much would you want? I'm not really willing to add this property as it would require more work around - the already complicated - state (remove observer and maybe recreate a new one - with everything that implies).

**Comment by delannoyk** [comment]
Closing this.
Re-open if you really feel like 0.5 is not enough.
