### ISSUE TITLE
Usage not working

### ISSUE THREAD

**Issue by k1nk4** [delannoyk/AudioPlayer#95]
let audioPlayer = AudioPlayer()
            
            let delegate : AudioPlayerDelegate = self
            
            audioPlayer.delegate = delegate
            
            let item = AudioItem(lowQualitySoundURL: url)
            
            audioPlayer.play(item: item!)

Its not playing anything. Whats wrong?

**Comment by delannoyk** [comment]
You have to keep a reference to the audio player instance so that it's not deallocated.
