### ISSUE TITLE
How to check for error in Swift 3

### ISSUE THREAD

**Issue by anasqadrei** [delannoyk/AudioPlayer#96]
Prior to swift 3, I was checking for any kind of error like this:
```
func audioPlayer(_ audioPlayer: AudioPlayer, didChangeStateFrom from: AudioPlayerState, to state: AudioPlayerState) {
    if state == .failed(.foundationError(nil)) {
         // handle error   
    }
}
```
But after converting to swift 3, the `nil` always gives a compile time error. How to check for failed loading(regardless of the reason)?

**Comment by delannoyk** [comment]
`if case .failed = state` should do the trick

**Comment by anasqadrei** [comment]
Worked. Thanks.
