### ISSUE TITLE
AudioItem artwork with URL

### ISSUE THREAD

**Issue by FrancoisObob** [delannoyk/AudioPlayer#98]
Hi,
Actually every artwork of my tracks are remote images, so I want to fetch this artwork when the track start to play. What's the best way to load AudioItem image from URL ? 
Sorry, maybe this is trivial but I don't have any example of implementation ...
Thanks !

**Comment by delannoyk** [comment]
Hey Francois,
You can create your `AudioItem` instance, ask for the player to play, download your image on a background thread or read from any cache you might have and update the `AudioItem` instance you created before. `AudioPlayer` will be notified for that change and will update what is necessary.
Let me know if you have any more question!
