### ISSUE TITLE
How to fix it? please help me thank you.

### ISSUE THREAD

**Issue by paneaktae** [delannoyk/AudioPlayer#99]
When i use AudioPlayer play items(queue) the player have error.

follow :
![screen shot 2560-03-31 at 3 09 18 pm](https://cloud.githubusercontent.com/assets/11417557/24541972/0b05b576-1624-11e7-888c-012417cf3417.png)

code :
![screen shot 2560-03-31 at 3 09 54 pm](https://cloud.githubusercontent.com/assets/11417557/24541995/23f1586a-1624-11e7-90a6-e48ed2ff7987.png)

**Comment by delannoyk** [comment]
Hey,

From what I see, your URL has a custom scheme and is not HTTP(s)? Could you confirm?

**Comment by magorik** [comment]
Hello,
The solution is to change:

`URL(string: mediaDatas[i]["url_media"].stringValue)!`

to

`URL(fileURLWithPath: mediaDatas[i]["url_media"].stringValue)!`

Reason is that you need to play local file, i guess...

**Comment by delannoyk** [comment]
Well if your file is local then yes.
